---
abstract: 'Alternate method of processing command line arguments'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: '0'
  Test::Warnings: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Getopt-Alt
provides:
  Getopt::Alt:
    file: lib/Getopt/Alt.pm
    version: v0.2.3
  Getopt::Alt::Command:
    file: lib/Getopt/Alt/Command.pm
    version: v0.2.3
  Getopt::Alt::Dynamic:
    file: lib/Getopt/Alt/Dynamic.pm
    version: v0.2.3
  Getopt::Alt::Exception:
    file: lib/Getopt/Alt/Exception.pm
    version: v0.2.3
  Getopt::Alt::Option:
    file: lib/Getopt/Alt/Option.pm
    version: v0.2.3
recommends:
  Pod::Coverage: '0'
  Test::Kwalitee: '0'
  Test::Perl::Critic: '0'
  Test::Spelling: '0'
requires:
  Config::Any: '0'
  File::HomeDir: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Moose: '0'
  Moose::Role: '0'
  Path::Class: '0'
  Scalar::Util: '0'
  Tie::Handle::Scalar: '0'
  Try::Tiny: '0'
  parent: '0'
  perl: '5.006'
  version: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Getopt-Alt
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/Getopt-Alt.git
version: v0.2.3
